#!/usr/bin/env node
// Regenerates ../COPY.md from copy.js. COPY.md is a BUILD ARTIFACT - edit copy.js.
// Two copies of the same sentence drift; a generated file cannot.
//   node src/build-copy-md.js

const fs = require('fs');
const path = require('path');
const { OFFER, AUDIENCES, CONCEPTS, SIZES, fill } = require('./copy.js');

const out = [];
const w = (s = '') => out.push(s);

w('# Insomnia Masterclass ads — the copy deck');
w();
w('**Generated from `src/copy.js`. Do not edit this file by hand — edit the copy deck and run `node src/build-copy-md.js`.**');
w();
const distinct = CONCEPTS.filter((c) => !c.sameCopyAs).length;
w(`Three audiences × ${CONCEPTS.length} concepts × ${SIZES.length} sizes = **${AUDIENCES.length * CONCEPTS.length * SIZES.length} rendered ads**.`);
w();
w(`**${AUDIENCES.length * distinct} distinct copy sets.** The other ${AUDIENCES.length * (CONCEPTS.length - distinct)} are the photo cuts, `);
w('which run their parent concept\'s exact words so the A/B measures the photograph and nothing else.');
w();

w('## The offer');
w();
w('| Field | Value |');
w('|---|---|');
w(`| Event | Free Insomnia Masterclass, live on Zoom |`);
w(`| Date | ${OFFER.dateLong} (verified: 2026-08-26 is a Wednesday) |`);
w(`| Time | \`${OFFER.time}\` **fill before launch** |`);
w(`| Host | ${OFFER.host}, ${OFFER.credentialLong} |`);
w(`| Registration URL | \`${OFFER.regUrl}\` **fill before launch** — the masterclass opt-in page, NOT intrabalance.com/register |`);
w();
w('## Audiences');
w();
w('| Lane | Who | Credit line | Prescribes? |');
w('|---|---|---|---|');
w('| `physicians` | MD / DO | CME | yes |');
w('| `nps` | Nurse practitioners / APRNs | CME/CE | yes |');
w('| `allied` | Psychologists, PAs and coaches | CME/CE | mixed — no line in this lane depends on writing a script |');
w();
w('Meta targeting per lane:');
w();
for (const a of AUDIENCES) w(`- **${a.label}** — ${a.metaTargeting}`);
w();

for (const aud of AUDIENCES) {
  w('---');
  w();
  w(`# ${aud.label}`);
  w();
  for (const con of CONCEPTS) {
    const c = aud[con.key];
    w(`## ${con.key} — ${con.name}`);
    w();
    w(`*${con.surface}. Files: \`out/${aud.key}/${aud.key}__${con.slug}__*.png\`*`);
    if (con.sameCopyAs) {
      w();
      w(`> **Photo cut.** Identical copy to ${con.sameCopyAs}, with Dr. Bhopal's portrait. Run them against each other to measure the photograph.`);
    }
    w();
    w('### Ad fields (paste into Ads Manager)');
    w();
    w('**Primary text**');
    w();
    w('```');
    w(fill(c.adPrimary));
    w('```');
    w();
    w(`**Headline:** ${fill(c.adHeadline)}`);
    w();
    w(`**Description:** ${fill(c.adDescription)}`);
    w();
    w(`**CTA button:** ${c.adCta}`);
    w();
    w('### On-image text (already rendered into the PNGs)');
    w();
    if (c.eyebrow) w(`- **Eyebrow:** ${fill(c.eyebrow)}`);
    if (c.kicker) w(`- **Credential:** ${c.kicker} / ${c.kickerSub}`);
    w(`- **Headline:** ${fill(c.h.lead)} **${fill(c.h.accent)}**  *(second half carries the accent)*`);
    w(`- **Sub:** ${fill(c.sub)}`);
    if (c.checks) for (const k of c.checks) w(`- **Check:** ${fill(k).replace(/\*\*/g, '')}`);
    if (c.chip) w(`- **Chip:** ${fill(c.chip)}`);
    if (c.strip) w(`- **Strip:** ${fill(c.strip)}`);
    if (c.credit) w(`- **Credit:** ${fill(c.credit)}`);
    w(`- **Button:** ${fill(c.button)}`);
    w();
  }
}

w('---');
w();
w('## Sizes');
w();
w('| Size | Pixels | Placement |');
w('|---|---|---|');
for (const s of SIZES) w(`| ${s.key.split('_')[0]} | ${s.w}×${s.h} | ${s.placement} |`);
w();
w('1.91:1 (1200×628) for link and right-column placements is **not rendered**. See README, "Still open".');
w();

const file = path.resolve(__dirname, '..', 'COPY.md');
fs.writeFileSync(file, out.join('\n'));
console.log(`wrote ${file} (${out.length} lines, ${AUDIENCES.length * CONCEPTS.length} copy sets)`);
